version: '3.9'
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
    volumes:
     - ./redis-data:/var/lib/redis
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
